#!/bin/bash

# setup test directory

TEST_NAME=`basename $0 | cut -f '2-' -d '_'`

if [ -z "$TEST_NAME" ]
then
	echo "The basename of this testscript should not be empty!" >&2
	exit 1
fi

if [ -d results/$TEST_NAME ]
then
	rm -rf results/$TEST_NAME
fi

mkdir results/$TEST_NAME

cd results/$TEST_NAME

yes 1 | ./../../../bin/transcoding-init.sh
TRANSCODING_INIT_EXIT_CODE=$?

if [ ! "$TRANSCODING_INIT_EXIT_CODE" == "0" ]
then
	exit 1
fi

# run test in directory

mkdir -p assets/a-video-file/source assets/a-video-file/h264-baseline-3-0
ln -s ./../../../../../fixtures/big_buck_bunny.mp4 assets/a-video-file/source/big_buck_bunny.mp4

./../../../bin/transcoding.sh start-worker
TRANSCODING_EXIT_CODE=$?

if [ ! "$TRANSCODING_EXIT_CODE" == "0" ]
then
	exit 1
fi

exit 0